name: Deploy Node.js application to AWS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ubuntu
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/self-healing-nodejs-deployment
            
            # Ensure repo exists
            if [ ! -d ".git" ]; then
              git clone https://github.com/Sheren-04/self-healing-nodejs-deployment.git .
            fi

            # Get latest code cleanly
            git fetch --all
            git reset --hard origin/main

            # Restart app
            docker compose down
            docker compose up -d --build
           
